name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      PACKAGE: libccar-${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Install build tools (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Install build tools (Windows)
        if: matrix.os == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1.13.0

      - name: Build libccar (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          gcc -O2 -std=c99 -fPIC -shared build_libccar.c -o libccar.so -lm
          mkdir -p car_demo/lib
          cp libccar.so car_demo/lib/

      - name: Build libccar (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          clang -O2 -std=c99 -dynamiclib build_libccar.c -o libccar.dylib -lm
          mkdir -p car_demo/lib
          cp libccar.dylib car_demo/lib/

      - name: Build libccar (Windows)
        if: matrix.os == 'windows-latest'
        shell: cmd
        run: |
          cl /O2 /LD build_libccar.c /Fe:ccar.dll /link /IMPLIB:.\ccar.lib
          dir /s
          mkdir car_demo\lib
          copy ccar.dll car_demo\lib\
          copy ccar.lib car_demo\lib\

      - name: Build Rust project
        working-directory: car_demo
        run: cargo build --release

      - name: Package artifacts (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir -p "${{ env.PACKAGE }}"
          mv target/release/libccar_demo "${{ env.PACKAGE }}"
          mv libccar.so "${{ env.PACKAGE }}"

      - name: Package artifacts (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          mkdir -p "${{ env.PACKAGE }}"
          mv target/release/libccar_demo "${{ env.PACKAGE }}"
          mv libccar.dylib "${{ env.PACKAGE }}"

      - name: Package artifacts (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          mkdir -p "${{ env.PACKAGE }}"
          mv target/release/libccar_demo.exe "${{ env.PACKAGE }}"
          mv ccar.dll "${{ env.PACKAGE }}"
          mv ccar.lib "${{ env.PACKAGE }}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PACKAGE }}
          path: ${{ env.PACKAGE }}